version: "3.4"
services:
#HDFS
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: namenode
    volumes:
      - ./data/hdfs/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./data/conf/hadoop-hive.env
    ports:
      - "50070:50070"
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: datanode
    volumes:
      - ./data/hdfs/datanode:/hadoop/dfs/data
    env_file:
      - ./data/conf/hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    ports:
      - "50075:50075"

#HIVE
  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive_server
    env_file:
      - ./data/conf/hadoop-hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"
  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive_metastore
    hostname: hive_metastore
    env_file:
      - ./data/conf/hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432"
    ports:
      - "9083:9083"
  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0
    container_name: hive_metastore_postgresql
    volumes:
      - ./data/hive-metastore-postgresql/data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 500m

  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
    env_file:
      - ./data/conf/postgres.env
    ports:
      - "5433:5432"

#HUE
  hue:
    image: gethue/hue:latest
    hostname: hue
    container_name: hue
    ports:
      - "8888:8888"
    network_mode: "host"
    depends_on:
      - postgres
    volumes:
      - ./data/conf/hue.ini:/usr/share/hue/desktop/conf/z-hue.ini
    deploy:
      resources:
        limits:
          memory: 500m

#SPARK
  spark-master:
    image: bde2020/spark-master:3.0.2-hadoop3.2
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4040:4040"
    volumes:
      - ./data/conf:/spark/conf
    environment:
      - INIT_DAEMON_STEP=setup_spark
    depends_on:
      - namenode
      - datanode
    env_file:
      - ./data/conf/jupyter.env

  spark-worker-1:
    image: bde2020/spark-worker:3.0.2-hadoop3.2
    container_name: spark-worker-1
    depends_on:
      - spark-master
      - namenode
      - datanode
    ports:
      - "8081:8081"
    volumes: 
      - ./data/conf:/spark/conf
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    env_file:
      - ./data/conf/jupyter.env

  spark-worker-2:
    image: bde2020/spark-worker:3.0.2-hadoop3.2
    container_name: spark-worker-2
    depends_on:
      - spark-master
      - namenode
      - datanode
    ports:
      - "8082:8081"
    volumes: 
      - ./data/conf:/spark/conf
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    env_file:
      - ./data/conf/jupyter.env

#NOTEBOOK / SPARK
  spark-notebook:
    image: jupyter/all-spark-notebook
    container_name: spark-notebook
    depends_on:
      - namenode
      - datanode
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    volumes:
      - ./data/conf:/usr/local/spark/conf
      - ./data/notebooks:/home/jovyan
      - ./data/dataset:/dataset
      - ./data/jupyter:/opt/conda/etc/jupyter/
    ports:
      - 8889:8888
      - 4049:4040

#HBASE
  zoo:
    image: zookeeper:3.4.10
    container_name: zoo
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888
    ports:
      - 2181:2181

  hbase-master:
    image: bde2020/hbase-master:1.0.0-hbase1.2.6
    container_name: hbase-master
    hostname: hbase-master
    depends_on:
      - namenode
      - datanode
      - zoo
    env_file:
      - ./data/conf/hbase-distributed-local.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 zoo:2181"
    ports:
      - 16010:16010

  hbase-region:
    image: bde2020/hbase-regionserver:1.0.0-hbase1.2.6
    container_name: hbase-regionserver
    hostname: hbase-regionserver
    depends_on:
      - namenode
      - datanode
      - zoo
      - hbase-master
    env_file:
      - ./data/conf/hbase-distributed-local.env
    environment:
      HBASE_CONF_hbase_regionserver_hostname: hbase-region
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 zoo:2181 hbase-master:16010"
    ports:
      - 16030:16030

volumes:
  shared_data: