version: "3.4"
services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: namenode
    volumes:
      - ./data/hdfs/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop-hive.env
    ports:
      - "50070:50070"

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: datanode
    volumes:
      - ./data/hdfs/datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    ports:
      - "50075:50075"
      
  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive_server
    env_file:
      - ./hadoop-hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"
  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive_metastore
    hostname: hive_metastore
    env_file:
      - ./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432"
    ports:
      - "9083:9083"
  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0
    container_name: hive_metastore_postgresql
    volumes:
      - ./data/postgresql/data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 500m

  postgres:
    image: postgres
    container_name: postgres
    env_file:
      - ./postgres.env
    ports:
      - "5433:5432"

  hue:
    image: gethue/hue:latest
    hostname: hue
    container_name: hue
    ports:
      - "8888:8888"
    network_mode: "host"
    depends_on:
      - postgres
    volumes:
      - ./hue.ini:/usr/share/hue/desktop/conf/z-hue.ini
    deploy:
      resources:
        limits:
          memory: 500m

#docker exec -it spark-master /spark/bin/spark-shell --master spark://spark-master:7077
  spark-master:
    image: bde2020/spark-master:3.0.2-hadoop3.2
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4040:4040"
    volumes:
      - shared_data:/data
      - ./data/spark/conf:/spark/conf
    environment:
      - INIT_DAEMON_STEP=setup_spark
      # - "constraint:node==<yourmasternode>"
    deploy:
      resources:
        limits:
          memory: 500m

  spark-worker-1:
    image: bde2020/spark-worker:3.0.2-hadoop3.2
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes: 
      - shared_data:/data
      - ./data/spark/conf:/spark/conf
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      # - "constraint:node==<yourworkernode>"
    deploy:
      resources:
        limits:
          memory: 500m

  spark-worker-2:
    image: bde2020/spark-worker:3.0.2-hadoop3.2
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    volumes: 
      - shared_data:/data
      - ./data/spark/conf:/spark/conf
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      # - "constraint:node==<yourworkernode>"
    deploy:
      resources:
        limits:
          memory: 500m

volumes:
  shared_data:
  # namenode:
  # datanode: